### PR TITLE
Update upstream/FernFlower

### PR DESCRIPTION
**Pull request by CDAGaming**

### CODE REVIEW

**Comment by jamierocks** [comment]
This cannot be done until the next Minecraft version, as it will alter the decompiled code.

**Comment by CDAGaming** [comment]
Ah Ok
I guess we can leave this open until that time period

**Comment by jamierocks** [comment]
You could, but the lack of altered patches would suggest to me that this isn't a complete merge - and it would likely be easier for lex to merge it himself.

**Comment by LexManos** [comment]
https://github.com/MinecraftForge/ForgeFlower/commit/5f139bc1b8e5b91f10f8c166f53703081448d0ea

**Pull request closed without merging**
