### PR TITLE
Fix some field initializers not being extracted or incorrectly extracted

### LINKED ISSUE #32: Field initalizers arnt properly extracted.
When class has multiple constructors, and one calls the other
See 1.13.1 GuiTextField
```   public GuiTextField(int p_i45542_1_, FontRenderer p_i45542_2_, int p_i45542_3_, int p_i45542_4_, int p_i45542_5_, int p_i45542_6_) {
      this(p_i45542_1_, p_i45542_2_, p_i45542_3_, p_i45542_4_, p_i45542_5_, p_i45542_6_, (GuiTextField)null);
   }

   public GuiTextField(int p_i49853_1_, FontRenderer p_i49853_2_, int p_i49853_3_, int p_i49853_4_, int p_i49853_5_, int p_i49853_6_, @Nullable GuiTextField p_i49853_7_) {
      this.field_146216_j = "";
      this.field_146217_k = 32;
      this.field_146215_m = true;
      this.field_146212_n = true;
      this.field_146226_p = true;
      this.field_146222_t = 14737632;
      this.field_146221_u = 7368816;
      this.field_146220_v = true;
      this.field_175209_y = Predicates.<String>alwaysTrue();
      this.field_195613_A = (p_195610_0_, p_195610_1_) -> {
         return p_195610_0_;
      };
//Everything above this should be extracted
      this.field_175208_g = p_i49853_1_;
      this.field_146211_a = p_i49853_2_;
      this.field_146209_f = p_i49853_3_;
      this.field_146210_g = p_i49853_4_;
      this.field_146218_h = p_i49853_5_;
      this.field_146219_i = p_i49853_6_;
      if (p_i49853_7_ != null) {
         this.func_146180_a(p_i49853_7_.func_146179_b());
      }

   }
```

### PR DESCRIPTION
**Pull request by JDLogic**
Should resolve #32.
[1.13.1 Diff](https://gist.github.com/JDLogic/7b59ef3641b430905e829b2ee546c922)

### CODE REVIEW

**Comment by kashike** [comment]
What about cases like in `World`? 
Seems like
```java
        this.eventListeners = Lists.newArrayList(this.pathListener);
        this.calendar = Calendar.getInstance();
        this.worldScoreboard = new Scoreboard();
        this.spawnHostileMobs = true;
        this.spawnPeacefulMobs = true;
        this.lightUpdateBlockList = new int[32768];
```
should be extracted too?

**Comment by JDLogic** [comment]
You are correct, and those cases should be fixed now as well. Also, while taking a closer look, I did notice that some initializers that should have not been extracted. Like `field_195842_d` in `LibraryLWJGL3 `. This should be fixed now too, and the diff has been updated to reflect the changes.

**Comment by bs2609** [comment]
Having a look through the current diff, are `IntHashMap` and `FoodStats` correct?

**Comment by JDLogic** [comment]
Yes. I may be doing something wrong, but from what I can tell, extracting those initializers produces different bytecode. Comparing to the original indicates that they should not be extracted.

Original vs FF before
ihm-before
Original vs FF after
ihm-after

**Pull request merged**
